### ISSUE TITLE
Update JuliaFormater options

### ISSUE THREAD

**Issue by datejada** [TulipaEnergy/TulipaEnergyModel.jl#940] opened 2024-12-04 07:37 UTC
### Description

Update JuliaFromater options to consider the option discussed here: https://github.com/TulipaEnergy/TulipaEnergyModel.jl/pull/928#discussion_r1867473654

**Comment by abelsiqueira** [comment] 2024-12-04 08:47
I think this is a duplicate of #796, unless you want to add other options

**Closed** 2024-12-19 14:34 UTC
Labels: good first issue
